version: "3.8"

services:
  postgres:
    image: postgres:15.2
    container_name: legsy-test-task-db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - legsy-test-task-volume:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  legsy-test-task-volume:
